### ISSUE TITLE
build failed on 7.4

### ISSUE THREAD

**Issue by lfarkas** [nkadel/gnutls-3.4.x-srpm#1]
build failed on 7.4 with one test:
FAIL: ocsp
or do you have an actual rpms of samba with ad dc on rhel/centos 7.4?
thanks in advance.
regards.

**Comment by nkadel** [comment]
On Tue, Oct 10, 2017 at 8:02 AM, Levente Farkas <notifications@github.com>
wrote:

> build failed on 7.4 with one test:
> FAIL: ocsp
> or do you have an actual rpms of samba with ad dc on rhel/centos 7.4?
> thanks in advance.
> regards.
>
>
> I set aside that project after current Samba releases updated the gnutls
requirement beyond the defaults for RHEL 7. I've not gone back, beside I
haven't needed it professionally or personally. Feel free to work with it,
I'd accept reasonable pull requests. Sernet also publishes RPM's for Samba
4.7.0, you might investigate those.

**Comment by nkadel** [comment]
It's time to kill off this repo: I can't reliably keep gnutls updated beyond the built-in version for RHEL 7, even to support full directory controller support for current Samba releases, due to the much more recent version needed for Samba 4.8.
